/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import { faker } from '@faker-js/faker';
import { HttpResponse, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import { customAxios } from '../axios.client';
import type {
  AcceptInvitation400,
  AcceptInvitation401,
  AcceptInvitation404,
  AcceptInvitation500,
  AcceptInvitationBody,
  InviteUserOwner400,
  InviteUserOwner401,
  InviteUserOwner404,
  InviteUserOwner500,
  InviteUserOwnerBody,
  ValidateInvitation400,
  ValidateInvitation401,
  ValidateInvitation404,
  ValidateInvitation500,
  ValidateInvitationBody,
} from '../model';
import type {
  AcceptInvitation200,
  InviteUserOwner200,
  ValidateInvitation200,
} from '../model';

/**
 * @summary Validate an invitation
 */
export const validateInvitation = (
  validateInvitationBody: ValidateInvitationBody,
  signal?: AbortSignal,
) => {
  return customAxios<ValidateInvitation200>({
    url: `/api/v1/invitations/validate`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: validateInvitationBody,
    signal,
  });
};

export const getValidateInvitationMutationOptions = <
  TError =
    | ValidateInvitation400
    | ValidateInvitation401
    | ValidateInvitation404
    | ValidateInvitation500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof validateInvitation>>,
    TError,
    { data: ValidateInvitationBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof validateInvitation>>,
  TError,
  { data: ValidateInvitationBody },
  TContext
> => {
  const mutationKey = ['validateInvitation'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof validateInvitation>>,
    { data: ValidateInvitationBody }
  > = (props) => {
    const { data } = props ?? {};

    return validateInvitation(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ValidateInvitationMutationResult = NonNullable<
  Awaited<ReturnType<typeof validateInvitation>>
>;
export type ValidateInvitationMutationBody = ValidateInvitationBody;
export type ValidateInvitationMutationError =
  | ValidateInvitation400
  | ValidateInvitation401
  | ValidateInvitation404
  | ValidateInvitation500;

/**
 * @summary Validate an invitation
 */
export const useValidateInvitation = <
  TError =
    | ValidateInvitation400
    | ValidateInvitation401
    | ValidateInvitation404
    | ValidateInvitation500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof validateInvitation>>,
      TError,
      { data: ValidateInvitationBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof validateInvitation>>,
  TError,
  { data: ValidateInvitationBody },
  TContext
> => {
  return useMutation(getValidateInvitationMutationOptions(options), queryClient);
};
/**
 * @summary Accept an invitation
 */
export const acceptInvitation = (
  acceptInvitationBody: AcceptInvitationBody,
  signal?: AbortSignal,
) => {
  return customAxios<AcceptInvitation200>({
    url: `/api/v1/invitations/accept`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: acceptInvitationBody,
    signal,
  });
};

export const getAcceptInvitationMutationOptions = <
  TError =
    | AcceptInvitation400
    | AcceptInvitation401
    | AcceptInvitation404
    | AcceptInvitation500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof acceptInvitation>>,
    TError,
    { data: AcceptInvitationBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof acceptInvitation>>,
  TError,
  { data: AcceptInvitationBody },
  TContext
> => {
  const mutationKey = ['acceptInvitation'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof acceptInvitation>>,
    { data: AcceptInvitationBody }
  > = (props) => {
    const { data } = props ?? {};

    return acceptInvitation(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AcceptInvitationMutationResult = NonNullable<
  Awaited<ReturnType<typeof acceptInvitation>>
>;
export type AcceptInvitationMutationBody = AcceptInvitationBody;
export type AcceptInvitationMutationError =
  | AcceptInvitation400
  | AcceptInvitation401
  | AcceptInvitation404
  | AcceptInvitation500;

/**
 * @summary Accept an invitation
 */
export const useAcceptInvitation = <
  TError =
    | AcceptInvitation400
    | AcceptInvitation401
    | AcceptInvitation404
    | AcceptInvitation500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof acceptInvitation>>,
      TError,
      { data: AcceptInvitationBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof acceptInvitation>>,
  TError,
  { data: AcceptInvitationBody },
  TContext
> => {
  return useMutation(getAcceptInvitationMutationOptions(options), queryClient);
};
/**
 * @summary Invite a new user owner
 */
export const inviteUserOwner = (
  inviteUserOwnerBody: InviteUserOwnerBody,
  signal?: AbortSignal,
) => {
  return customAxios<InviteUserOwner200>({
    url: `/api/v1/invitations`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: inviteUserOwnerBody,
    signal,
  });
};

export const getInviteUserOwnerMutationOptions = <
  TError =
    | InviteUserOwner400
    | InviteUserOwner401
    | InviteUserOwner404
    | InviteUserOwner500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof inviteUserOwner>>,
    TError,
    { data: InviteUserOwnerBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof inviteUserOwner>>,
  TError,
  { data: InviteUserOwnerBody },
  TContext
> => {
  const mutationKey = ['inviteUserOwner'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof inviteUserOwner>>,
    { data: InviteUserOwnerBody }
  > = (props) => {
    const { data } = props ?? {};

    return inviteUserOwner(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type InviteUserOwnerMutationResult = NonNullable<
  Awaited<ReturnType<typeof inviteUserOwner>>
>;
export type InviteUserOwnerMutationBody = InviteUserOwnerBody;
export type InviteUserOwnerMutationError =
  | InviteUserOwner400
  | InviteUserOwner401
  | InviteUserOwner404
  | InviteUserOwner500;

/**
 * @summary Invite a new user owner
 */
export const useInviteUserOwner = <
  TError =
    | InviteUserOwner400
    | InviteUserOwner401
    | InviteUserOwner404
    | InviteUserOwner500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof inviteUserOwner>>,
      TError,
      { data: InviteUserOwnerBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof inviteUserOwner>>,
  TError,
  { data: InviteUserOwnerBody },
  TContext
> => {
  return useMutation(getInviteUserOwnerMutationOptions(options), queryClient);
};

export const getValidateInvitationResponseMock = (
  overrideResponse: Partial<ValidateInvitation200> = {},
): ValidateInvitation200 => ({
  success: faker.datatype.boolean(),
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  data: {
    email: faker.internet.email(),
    roleName: faker.string.alpha({ length: { min: 10, max: 20 } }),
    isNewCompany: faker.datatype.boolean(),
  },
  meta: { timestamp: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  ...overrideResponse,
});

export const getAcceptInvitationResponseMock = (
  overrideResponse: Partial<AcceptInvitation200> = {},
): AcceptInvitation200 => ({
  success: faker.datatype.boolean(),
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  data: {
    acceptedAt: faker.date.past().toISOString().slice(0, 19) + 'Z',
    invitationStatus: faker.string.alpha({ length: { min: 10, max: 20 } }),
  },
  meta: { timestamp: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  ...overrideResponse,
});

export const getInviteUserOwnerResponseMock = (
  overrideResponse: Partial<InviteUserOwner200> = {},
): InviteUserOwner200 => ({
  success: faker.datatype.boolean(),
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  data: { email: faker.internet.email() },
  meta: { timestamp: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  ...overrideResponse,
});

export const getValidateInvitationMockHandler = (
  overrideResponse?:
    | ValidateInvitation200
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ValidateInvitation200> | ValidateInvitation200),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/api/v1/invitations/validate',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getValidateInvitationResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getAcceptInvitationMockHandler = (
  overrideResponse?:
    | AcceptInvitation200
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<AcceptInvitation200> | AcceptInvitation200),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/api/v1/invitations/accept',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getAcceptInvitationResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getInviteUserOwnerMockHandler = (
  overrideResponse?:
    | InviteUserOwner200
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<InviteUserOwner200> | InviteUserOwner200),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/api/v1/invitations',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getInviteUserOwnerResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};
export const getInvitationsMock = () => [
  getValidateInvitationMockHandler(),
  getAcceptInvitationMockHandler(),
  getInviteUserOwnerMockHandler(),
];
