/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import { faker } from '@faker-js/faker';
import { HttpResponse, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import { customAxios } from '../axios.client';
import type {
  AcceptInvitation400,
  AcceptInvitation401,
  AcceptInvitation404,
  AcceptInvitation500,
  AcceptInvitationBody,
  InviteUser400,
  InviteUser401,
  InviteUser404,
  InviteUser500,
  InviteUserBody,
  ValidateInvitation400,
  ValidateInvitation401,
  ValidateInvitation404,
  ValidateInvitation500,
  ValidateInvitationBody,
} from '../model';
import type { ValidateInvitation200 } from '../model';

/**
 * @summary Validate an invitation
 */
export const validateInvitation = (
  validateInvitationBody: ValidateInvitationBody,
  signal?: AbortSignal,
) => {
  return customAxios<ValidateInvitation200>({
    url: `/api/v1/invitations/validate`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: validateInvitationBody,
    signal,
  });
};

export const getValidateInvitationMutationOptions = <
  TError =
    | ValidateInvitation400
    | ValidateInvitation401
    | ValidateInvitation404
    | ValidateInvitation500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof validateInvitation>>,
    TError,
    { data: ValidateInvitationBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof validateInvitation>>,
  TError,
  { data: ValidateInvitationBody },
  TContext
> => {
  const mutationKey = ['validateInvitation'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof validateInvitation>>,
    { data: ValidateInvitationBody }
  > = (props) => {
    const { data } = props ?? {};

    return validateInvitation(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ValidateInvitationMutationResult = NonNullable<
  Awaited<ReturnType<typeof validateInvitation>>
>;
export type ValidateInvitationMutationBody = ValidateInvitationBody;
export type ValidateInvitationMutationError =
  | ValidateInvitation400
  | ValidateInvitation401
  | ValidateInvitation404
  | ValidateInvitation500;

/**
 * @summary Validate an invitation
 */
export const useValidateInvitation = <
  TError =
    | ValidateInvitation400
    | ValidateInvitation401
    | ValidateInvitation404
    | ValidateInvitation500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof validateInvitation>>,
      TError,
      { data: ValidateInvitationBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof validateInvitation>>,
  TError,
  { data: ValidateInvitationBody },
  TContext
> => {
  return useMutation(getValidateInvitationMutationOptions(options), queryClient);
};
/**
 * @summary Accept an invitation
 */
export const acceptInvitation = (
  acceptInvitationBody: AcceptInvitationBody,
  signal?: AbortSignal,
) => {
  return customAxios<void>({
    url: `/api/v1/invitations/accept`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: acceptInvitationBody,
    signal,
  });
};

export const getAcceptInvitationMutationOptions = <
  TError =
    | AcceptInvitation400
    | AcceptInvitation401
    | AcceptInvitation404
    | AcceptInvitation500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof acceptInvitation>>,
    TError,
    { data: AcceptInvitationBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof acceptInvitation>>,
  TError,
  { data: AcceptInvitationBody },
  TContext
> => {
  const mutationKey = ['acceptInvitation'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof acceptInvitation>>,
    { data: AcceptInvitationBody }
  > = (props) => {
    const { data } = props ?? {};

    return acceptInvitation(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AcceptInvitationMutationResult = NonNullable<
  Awaited<ReturnType<typeof acceptInvitation>>
>;
export type AcceptInvitationMutationBody = AcceptInvitationBody;
export type AcceptInvitationMutationError =
  | AcceptInvitation400
  | AcceptInvitation401
  | AcceptInvitation404
  | AcceptInvitation500;

/**
 * @summary Accept an invitation
 */
export const useAcceptInvitation = <
  TError =
    | AcceptInvitation400
    | AcceptInvitation401
    | AcceptInvitation404
    | AcceptInvitation500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof acceptInvitation>>,
      TError,
      { data: AcceptInvitationBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof acceptInvitation>>,
  TError,
  { data: AcceptInvitationBody },
  TContext
> => {
  return useMutation(getAcceptInvitationMutationOptions(options), queryClient);
};
/**
 * @summary Invite a new user
 */
export const inviteUser = (inviteUserBody: InviteUserBody, signal?: AbortSignal) => {
  return customAxios<void>({
    url: `/api/v1/invitations`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: inviteUserBody,
    signal,
  });
};

export const getInviteUserMutationOptions = <
  TError = InviteUser400 | InviteUser401 | InviteUser404 | InviteUser500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof inviteUser>>,
    TError,
    { data: InviteUserBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof inviteUser>>,
  TError,
  { data: InviteUserBody },
  TContext
> => {
  const mutationKey = ['inviteUser'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof inviteUser>>,
    { data: InviteUserBody }
  > = (props) => {
    const { data } = props ?? {};

    return inviteUser(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type InviteUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof inviteUser>>
>;
export type InviteUserMutationBody = InviteUserBody;
export type InviteUserMutationError =
  | InviteUser400
  | InviteUser401
  | InviteUser404
  | InviteUser500;

/**
 * @summary Invite a new user
 */
export const useInviteUser = <
  TError = InviteUser400 | InviteUser401 | InviteUser404 | InviteUser500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof inviteUser>>,
      TError,
      { data: InviteUserBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof inviteUser>>,
  TError,
  { data: InviteUserBody },
  TContext
> => {
  return useMutation(getInviteUserMutationOptions(options), queryClient);
};

export const getValidateInvitationResponseMock = (
  overrideResponse: Partial<ValidateInvitation200> = {},
): ValidateInvitation200 => ({
  email: faker.internet.email(),
  role: faker.helpers.arrayElement([
    'owner',
    'manager',
    'warehouse',
    'branch_staff',
  ] as const),
  ...overrideResponse,
});

export const getValidateInvitationMockHandler = (
  overrideResponse?:
    | ValidateInvitation200
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ValidateInvitation200> | ValidateInvitation200),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/api/v1/invitations/validate',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getValidateInvitationResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getAcceptInvitationMockHandler = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/api/v1/invitations/accept',
    async (info) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 204 });
    },
    options,
  );
};

export const getInviteUserMockHandler = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/api/v1/invitations',
    async (info) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 204 });
    },
    options,
  );
};
export const getInvitationsMock = () => [
  getValidateInvitationMockHandler(),
  getAcceptInvitationMockHandler(),
  getInviteUserMockHandler(),
];
