/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import { faker } from '@faker-js/faker';
import { HttpResponse, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customAxios } from '../axios.client';
import type {
  GetOnboardingStatus401,
  GetOnboardingStatus404,
  GetOnboardingStatus500,
  UpdateCompany400,
  UpdateCompany401,
  UpdateCompany404,
  UpdateCompany500,
  UpdateCompanyBody,
  UpdatePreferences400,
  UpdatePreferences401,
  UpdatePreferences404,
  UpdatePreferences500,
  UpdatePreferencesBody,
  UpdateProfile400,
  UpdateProfile401,
  UpdateProfile404,
  UpdateProfile500,
  UpdateProfileBody,
} from '../model';
import type { GetOnboardingStatus200 } from '../model';

/**
 * @summary Get onboarding completion status
 */
export const getOnboardingStatus = (signal?: AbortSignal) => {
  return customAxios<GetOnboardingStatus200>({
    url: `/api/v1/onboarding/status`,
    method: 'GET',
    signal,
  });
};

export const getGetOnboardingStatusQueryKey = () => {
  return [`/api/v1/onboarding/status`] as const;
};

export const getGetOnboardingStatusQueryOptions = <
  TData = Awaited<ReturnType<typeof getOnboardingStatus>>,
  TError = GetOnboardingStatus401 | GetOnboardingStatus404 | GetOnboardingStatus500,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getOnboardingStatus>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetOnboardingStatusQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getOnboardingStatus>>> = ({
    signal,
  }) => getOnboardingStatus(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getOnboardingStatus>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetOnboardingStatusQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOnboardingStatus>>
>;
export type GetOnboardingStatusQueryError =
  | GetOnboardingStatus401
  | GetOnboardingStatus404
  | GetOnboardingStatus500;

export function useGetOnboardingStatus<
  TData = Awaited<ReturnType<typeof getOnboardingStatus>>,
  TError = GetOnboardingStatus401 | GetOnboardingStatus404 | GetOnboardingStatus500,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOnboardingStatus>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOnboardingStatus>>,
          TError,
          Awaited<ReturnType<typeof getOnboardingStatus>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOnboardingStatus<
  TData = Awaited<ReturnType<typeof getOnboardingStatus>>,
  TError = GetOnboardingStatus401 | GetOnboardingStatus404 | GetOnboardingStatus500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOnboardingStatus>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOnboardingStatus>>,
          TError,
          Awaited<ReturnType<typeof getOnboardingStatus>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOnboardingStatus<
  TData = Awaited<ReturnType<typeof getOnboardingStatus>>,
  TError = GetOnboardingStatus401 | GetOnboardingStatus404 | GetOnboardingStatus500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOnboardingStatus>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get onboarding completion status
 */

export function useGetOnboardingStatus<
  TData = Awaited<ReturnType<typeof getOnboardingStatus>>,
  TError = GetOnboardingStatus401 | GetOnboardingStatus404 | GetOnboardingStatus500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOnboardingStatus>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetOnboardingStatusQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update company info during onboarding
 */
export const updateCompany = (
  updateCompanyBody: UpdateCompanyBody,
  signal?: AbortSignal,
) => {
  return customAxios<void>({
    url: `/api/v1/onboarding/company`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updateCompanyBody,
    signal,
  });
};

export const getUpdateCompanyMutationOptions = <
  TError = UpdateCompany400 | UpdateCompany401 | UpdateCompany404 | UpdateCompany500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCompany>>,
    TError,
    { data: UpdateCompanyBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateCompany>>,
  TError,
  { data: UpdateCompanyBody },
  TContext
> => {
  const mutationKey = ['updateCompany'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateCompany>>,
    { data: UpdateCompanyBody }
  > = (props) => {
    const { data } = props ?? {};

    return updateCompany(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateCompanyMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateCompany>>
>;
export type UpdateCompanyMutationBody = UpdateCompanyBody;
export type UpdateCompanyMutationError =
  | UpdateCompany400
  | UpdateCompany401
  | UpdateCompany404
  | UpdateCompany500;

/**
 * @summary Update company info during onboarding
 */
export const useUpdateCompany = <
  TError = UpdateCompany400 | UpdateCompany401 | UpdateCompany404 | UpdateCompany500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateCompany>>,
      TError,
      { data: UpdateCompanyBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateCompany>>,
  TError,
  { data: UpdateCompanyBody },
  TContext
> => {
  return useMutation(getUpdateCompanyMutationOptions(options), queryClient);
};
/**
 * @summary Update user profile during onboarding
 */
export const updateProfile = (
  updateProfileBody: UpdateProfileBody,
  signal?: AbortSignal,
) => {
  return customAxios<void>({
    url: `/api/v1/onboarding/profile`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updateProfileBody,
    signal,
  });
};

export const getUpdateProfileMutationOptions = <
  TError = UpdateProfile400 | UpdateProfile401 | UpdateProfile404 | UpdateProfile500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProfile>>,
    TError,
    { data: UpdateProfileBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateProfile>>,
  TError,
  { data: UpdateProfileBody },
  TContext
> => {
  const mutationKey = ['updateProfile'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateProfile>>,
    { data: UpdateProfileBody }
  > = (props) => {
    const { data } = props ?? {};

    return updateProfile(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateProfileMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateProfile>>
>;
export type UpdateProfileMutationBody = UpdateProfileBody;
export type UpdateProfileMutationError =
  | UpdateProfile400
  | UpdateProfile401
  | UpdateProfile404
  | UpdateProfile500;

/**
 * @summary Update user profile during onboarding
 */
export const useUpdateProfile = <
  TError = UpdateProfile400 | UpdateProfile401 | UpdateProfile404 | UpdateProfile500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateProfile>>,
      TError,
      { data: UpdateProfileBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateProfile>>,
  TError,
  { data: UpdateProfileBody },
  TContext
> => {
  return useMutation(getUpdateProfileMutationOptions(options), queryClient);
};
/**
 * @summary Save user preferences during onboarding
 */
export const updatePreferences = (
  updatePreferencesBody: UpdatePreferencesBody,
  signal?: AbortSignal,
) => {
  return customAxios<void>({
    url: `/api/v1/onboarding/preferences`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updatePreferencesBody,
    signal,
  });
};

export const getUpdatePreferencesMutationOptions = <
  TError =
    | UpdatePreferences400
    | UpdatePreferences401
    | UpdatePreferences404
    | UpdatePreferences500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updatePreferences>>,
    TError,
    { data: UpdatePreferencesBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updatePreferences>>,
  TError,
  { data: UpdatePreferencesBody },
  TContext
> => {
  const mutationKey = ['updatePreferences'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updatePreferences>>,
    { data: UpdatePreferencesBody }
  > = (props) => {
    const { data } = props ?? {};

    return updatePreferences(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdatePreferencesMutationResult = NonNullable<
  Awaited<ReturnType<typeof updatePreferences>>
>;
export type UpdatePreferencesMutationBody = UpdatePreferencesBody;
export type UpdatePreferencesMutationError =
  | UpdatePreferences400
  | UpdatePreferences401
  | UpdatePreferences404
  | UpdatePreferences500;

/**
 * @summary Save user preferences during onboarding
 */
export const useUpdatePreferences = <
  TError =
    | UpdatePreferences400
    | UpdatePreferences401
    | UpdatePreferences404
    | UpdatePreferences500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updatePreferences>>,
      TError,
      { data: UpdatePreferencesBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updatePreferences>>,
  TError,
  { data: UpdatePreferencesBody },
  TContext
> => {
  return useMutation(getUpdatePreferencesMutationOptions(options), queryClient);
};

export const getGetOnboardingStatusResponseMock = (
  overrideResponse: Partial<GetOnboardingStatus200> = {},
): GetOnboardingStatus200 => ({
  success: faker.datatype.boolean(),
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  data: {
    company_completed: faker.datatype.boolean(),
    profile_completed: faker.datatype.boolean(),
    preferences_completed: faker.datatype.boolean(),
    onboarding_completed: faker.datatype.boolean(),
  },
  meta: { timestamp: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  ...overrideResponse,
});

export const getGetOnboardingStatusMockHandler = (
  overrideResponse?:
    | GetOnboardingStatus200
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<GetOnboardingStatus200> | GetOnboardingStatus200),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/v1/onboarding/status',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetOnboardingStatusResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getUpdateCompanyMockHandler = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    '*/api/v1/onboarding/company',
    async (info) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 204 });
    },
    options,
  );
};

export const getUpdateProfileMockHandler = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    '*/api/v1/onboarding/profile',
    async (info) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 204 });
    },
    options,
  );
};

export const getUpdatePreferencesMockHandler = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    '*/api/v1/onboarding/preferences',
    async (info) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 204 });
    },
    options,
  );
};
export const getOnboardingMock = () => [
  getGetOnboardingStatusMockHandler(),
  getUpdateCompanyMockHandler(),
  getUpdateProfileMockHandler(),
  getUpdatePreferencesMockHandler(),
];
