/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import { faker } from '@faker-js/faker';
import { HttpResponse, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customAxios } from '../axios.client';
import type {
  CreateOwner400,
  CreateOwner401,
  CreateOwner404,
  CreateOwner500,
  CreateOwnerBody,
  DeleteOwner401,
  DeleteOwner404,
  DeleteOwner500,
  GetMeOwner401,
  GetMeOwner404,
  GetMeOwner500,
  GetOwner401,
  GetOwner404,
  GetOwner500,
  ListOwners400,
  ListOwners401,
  ListOwners404,
  ListOwners500,
  ListOwnersParams,
  UpdateOwner400,
  UpdateOwner401,
  UpdateOwner404,
  UpdateOwner500,
  UpdateOwnerBody,
} from '../model';
import type {
  CreateOwner200,
  GetMeOwner200,
  GetOwner200,
  ListOwners200,
  UpdateOwner200,
} from '../model';

/**
 * @summary Get current owner
 */
export const getMeOwner = (signal?: AbortSignal) => {
  return customAxios<GetMeOwner200>({ url: `/api/v1/owners/me`, method: 'GET', signal });
};

export const getGetMeOwnerQueryKey = () => {
  return [`/api/v1/owners/me`] as const;
};

export const getGetMeOwnerQueryOptions = <
  TData = Awaited<ReturnType<typeof getMeOwner>>,
  TError = GetMeOwner401 | GetMeOwner404 | GetMeOwner500,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeOwner>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMeOwnerQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMeOwner>>> = ({ signal }) =>
    getMeOwner(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMeOwner>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMeOwnerQueryResult = NonNullable<Awaited<ReturnType<typeof getMeOwner>>>;
export type GetMeOwnerQueryError = GetMeOwner401 | GetMeOwner404 | GetMeOwner500;

export function useGetMeOwner<
  TData = Awaited<ReturnType<typeof getMeOwner>>,
  TError = GetMeOwner401 | GetMeOwner404 | GetMeOwner500,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMeOwner>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeOwner>>,
          TError,
          Awaited<ReturnType<typeof getMeOwner>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMeOwner<
  TData = Awaited<ReturnType<typeof getMeOwner>>,
  TError = GetMeOwner401 | GetMeOwner404 | GetMeOwner500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMeOwner>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeOwner>>,
          TError,
          Awaited<ReturnType<typeof getMeOwner>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMeOwner<
  TData = Awaited<ReturnType<typeof getMeOwner>>,
  TError = GetMeOwner401 | GetMeOwner404 | GetMeOwner500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMeOwner>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get current owner
 */

export function useGetMeOwner<
  TData = Awaited<ReturnType<typeof getMeOwner>>,
  TError = GetMeOwner401 | GetMeOwner404 | GetMeOwner500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMeOwner>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMeOwnerQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List owners
 */
export const listOwners = (params?: ListOwnersParams, signal?: AbortSignal) => {
  return customAxios<ListOwners200>({
    url: `/api/v1/owners`,
    method: 'GET',
    params,
    signal,
  });
};

export const getListOwnersQueryKey = (params?: ListOwnersParams) => {
  return [`/api/v1/owners`, ...(params ? [params] : [])] as const;
};

export const getListOwnersQueryOptions = <
  TData = Awaited<ReturnType<typeof listOwners>>,
  TError = ListOwners400 | ListOwners401 | ListOwners404 | ListOwners500,
>(
  params?: ListOwnersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listOwners>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListOwnersQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listOwners>>> = ({ signal }) =>
    listOwners(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listOwners>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListOwnersQueryResult = NonNullable<Awaited<ReturnType<typeof listOwners>>>;
export type ListOwnersQueryError =
  | ListOwners400
  | ListOwners401
  | ListOwners404
  | ListOwners500;

export function useListOwners<
  TData = Awaited<ReturnType<typeof listOwners>>,
  TError = ListOwners400 | ListOwners401 | ListOwners404 | ListOwners500,
>(
  params: undefined | ListOwnersParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listOwners>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listOwners>>,
          TError,
          Awaited<ReturnType<typeof listOwners>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListOwners<
  TData = Awaited<ReturnType<typeof listOwners>>,
  TError = ListOwners400 | ListOwners401 | ListOwners404 | ListOwners500,
>(
  params?: ListOwnersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listOwners>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listOwners>>,
          TError,
          Awaited<ReturnType<typeof listOwners>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListOwners<
  TData = Awaited<ReturnType<typeof listOwners>>,
  TError = ListOwners400 | ListOwners401 | ListOwners404 | ListOwners500,
>(
  params?: ListOwnersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listOwners>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List owners
 */

export function useListOwners<
  TData = Awaited<ReturnType<typeof listOwners>>,
  TError = ListOwners400 | ListOwners401 | ListOwners404 | ListOwners500,
>(
  params?: ListOwnersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listOwners>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListOwnersQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create an owner
 */
export const createOwner = (createOwnerBody: CreateOwnerBody, signal?: AbortSignal) => {
  return customAxios<CreateOwner200>({
    url: `/api/v1/owners`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createOwnerBody,
    signal,
  });
};

export const getCreateOwnerMutationOptions = <
  TError = CreateOwner400 | CreateOwner401 | CreateOwner404 | CreateOwner500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createOwner>>,
    TError,
    { data: CreateOwnerBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createOwner>>,
  TError,
  { data: CreateOwnerBody },
  TContext
> => {
  const mutationKey = ['createOwner'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createOwner>>,
    { data: CreateOwnerBody }
  > = (props) => {
    const { data } = props ?? {};

    return createOwner(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateOwnerMutationResult = NonNullable<
  Awaited<ReturnType<typeof createOwner>>
>;
export type CreateOwnerMutationBody = CreateOwnerBody;
export type CreateOwnerMutationError =
  | CreateOwner400
  | CreateOwner401
  | CreateOwner404
  | CreateOwner500;

/**
 * @summary Create an owner
 */
export const useCreateOwner = <
  TError = CreateOwner400 | CreateOwner401 | CreateOwner404 | CreateOwner500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createOwner>>,
      TError,
      { data: CreateOwnerBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createOwner>>,
  TError,
  { data: CreateOwnerBody },
  TContext
> => {
  return useMutation(getCreateOwnerMutationOptions(options), queryClient);
};
/**
 * @summary Get an owner
 */
export const getOwner = (id: string, signal?: AbortSignal) => {
  return customAxios<GetOwner200>({ url: `/api/v1/owners/${id}`, method: 'GET', signal });
};

export const getGetOwnerQueryKey = (id: string) => {
  return [`/api/v1/owners/${id}`] as const;
};

export const getGetOwnerQueryOptions = <
  TData = Awaited<ReturnType<typeof getOwner>>,
  TError = GetOwner401 | GetOwner404 | GetOwner500,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOwner>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetOwnerQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getOwner>>> = ({ signal }) =>
    getOwner(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getOwner>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetOwnerQueryResult = NonNullable<Awaited<ReturnType<typeof getOwner>>>;
export type GetOwnerQueryError = GetOwner401 | GetOwner404 | GetOwner500;

export function useGetOwner<
  TData = Awaited<ReturnType<typeof getOwner>>,
  TError = GetOwner401 | GetOwner404 | GetOwner500,
>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOwner>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOwner>>,
          TError,
          Awaited<ReturnType<typeof getOwner>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOwner<
  TData = Awaited<ReturnType<typeof getOwner>>,
  TError = GetOwner401 | GetOwner404 | GetOwner500,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOwner>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOwner>>,
          TError,
          Awaited<ReturnType<typeof getOwner>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOwner<
  TData = Awaited<ReturnType<typeof getOwner>>,
  TError = GetOwner401 | GetOwner404 | GetOwner500,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOwner>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get an owner
 */

export function useGetOwner<
  TData = Awaited<ReturnType<typeof getOwner>>,
  TError = GetOwner401 | GetOwner404 | GetOwner500,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOwner>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetOwnerQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update an owner
 */
export const updateOwner = (
  id: string,
  updateOwnerBody: UpdateOwnerBody,
  signal?: AbortSignal,
) => {
  return customAxios<UpdateOwner200>({
    url: `/api/v1/owners/${id}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updateOwnerBody,
    signal,
  });
};

export const getUpdateOwnerMutationOptions = <
  TError = UpdateOwner400 | UpdateOwner401 | UpdateOwner404 | UpdateOwner500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateOwner>>,
    TError,
    { id: string; data: UpdateOwnerBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateOwner>>,
  TError,
  { id: string; data: UpdateOwnerBody },
  TContext
> => {
  const mutationKey = ['updateOwner'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateOwner>>,
    { id: string; data: UpdateOwnerBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateOwner(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateOwnerMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateOwner>>
>;
export type UpdateOwnerMutationBody = UpdateOwnerBody;
export type UpdateOwnerMutationError =
  | UpdateOwner400
  | UpdateOwner401
  | UpdateOwner404
  | UpdateOwner500;

/**
 * @summary Update an owner
 */
export const useUpdateOwner = <
  TError = UpdateOwner400 | UpdateOwner401 | UpdateOwner404 | UpdateOwner500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateOwner>>,
      TError,
      { id: string; data: UpdateOwnerBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateOwner>>,
  TError,
  { id: string; data: UpdateOwnerBody },
  TContext
> => {
  return useMutation(getUpdateOwnerMutationOptions(options), queryClient);
};
/**
 * @summary Delete an owner
 */
export const deleteOwner = (id: string, signal?: AbortSignal) => {
  return customAxios<string>({ url: `/api/v1/owners/${id}`, method: 'DELETE', signal });
};

export const getDeleteOwnerMutationOptions = <
  TError = DeleteOwner401 | DeleteOwner404 | DeleteOwner500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteOwner>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteOwner>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['deleteOwner'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteOwner>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteOwner(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteOwnerMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteOwner>>
>;

export type DeleteOwnerMutationError = DeleteOwner401 | DeleteOwner404 | DeleteOwner500;

/**
 * @summary Delete an owner
 */
export const useDeleteOwner = <
  TError = DeleteOwner401 | DeleteOwner404 | DeleteOwner500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteOwner>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteOwner>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteOwnerMutationOptions(options), queryClient);
};

export const getGetMeOwnerResponseMock = (
  overrideResponse: Partial<GetMeOwner200> = {},
): GetMeOwner200 => ({
  id: faker.string.uuid(),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  email: faker.internet.email(),
  phone: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    null,
  ]),
  businessName: faker.string.alpha({ length: { min: 10, max: 20 } }),
  logoUrl: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    null,
  ]),
  isActive: faker.datatype.boolean(),
  createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z',
  updatedAt: faker.date.past().toISOString().slice(0, 19) + 'Z',
  ...overrideResponse,
});

export const getListOwnersResponseMock = (
  overrideResponse: Partial<ListOwners200> = {},
): ListOwners200 => ({
  id: faker.string.uuid(),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  email: faker.internet.email(),
  phone: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    null,
  ]),
  businessName: faker.string.alpha({ length: { min: 10, max: 20 } }),
  logoUrl: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    null,
  ]),
  isActive: faker.datatype.boolean(),
  createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z',
  updatedAt: faker.date.past().toISOString().slice(0, 19) + 'Z',
  ...overrideResponse,
});

export const getCreateOwnerResponseMock = (
  overrideResponse: Partial<CreateOwner200> = {},
): CreateOwner200 => ({
  id: faker.string.uuid(),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  email: faker.internet.email(),
  phone: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    null,
  ]),
  businessName: faker.string.alpha({ length: { min: 10, max: 20 } }),
  logoUrl: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    null,
  ]),
  isActive: faker.datatype.boolean(),
  createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z',
  updatedAt: faker.date.past().toISOString().slice(0, 19) + 'Z',
  ...overrideResponse,
});

export const getGetOwnerResponseMock = (
  overrideResponse: Partial<GetOwner200> = {},
): GetOwner200 => ({
  id: faker.string.uuid(),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  email: faker.internet.email(),
  phone: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    null,
  ]),
  businessName: faker.string.alpha({ length: { min: 10, max: 20 } }),
  logoUrl: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    null,
  ]),
  isActive: faker.datatype.boolean(),
  createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z',
  updatedAt: faker.date.past().toISOString().slice(0, 19) + 'Z',
  ...overrideResponse,
});

export const getUpdateOwnerResponseMock = (
  overrideResponse: Partial<UpdateOwner200> = {},
): UpdateOwner200 => ({
  id: faker.string.uuid(),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  email: faker.internet.email(),
  phone: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    null,
  ]),
  businessName: faker.string.alpha({ length: { min: 10, max: 20 } }),
  logoUrl: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    null,
  ]),
  isActive: faker.datatype.boolean(),
  createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z',
  updatedAt: faker.date.past().toISOString().slice(0, 19) + 'Z',
  ...overrideResponse,
});

export const getDeleteOwnerResponseMock = (): string => faker.word.sample();

export const getGetMeOwnerMockHandler = (
  overrideResponse?:
    | GetMeOwner200
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<GetMeOwner200> | GetMeOwner200),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/v1/owners/me',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetMeOwnerResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getListOwnersMockHandler = (
  overrideResponse?:
    | ListOwners200
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ListOwners200> | ListOwners200),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/v1/owners',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getListOwnersResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getCreateOwnerMockHandler = (
  overrideResponse?:
    | CreateOwner200
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<CreateOwner200> | CreateOwner200),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/api/v1/owners',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getCreateOwnerResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getGetOwnerMockHandler = (
  overrideResponse?:
    | GetOwner200
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<GetOwner200> | GetOwner200),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/v1/owners/:id',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetOwnerResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getUpdateOwnerMockHandler = (
  overrideResponse?:
    | UpdateOwner200
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<UpdateOwner200> | UpdateOwner200),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    '*/api/v1/owners/:id',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getUpdateOwnerResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getDeleteOwnerMockHandler = (
  overrideResponse?:
    | string
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<string> | string),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    '*/api/v1/owners/:id',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getDeleteOwnerResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};
export const getOwnersMock = () => [
  getGetMeOwnerMockHandler(),
  getListOwnersMockHandler(),
  getCreateOwnerMockHandler(),
  getGetOwnerMockHandler(),
  getUpdateOwnerMockHandler(),
  getDeleteOwnerMockHandler(),
];
