/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import { faker } from '@faker-js/faker';
import { HttpResponse, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customAxios } from '../axios.client';
import type {
  GetHealthCheckController400,
  GetHealthCheckController401,
  GetHealthCheckController404,
  GetHealthCheckController500,
} from '../model';
import type { GetHealthCheckController200 } from '../model';

/**
 * @summary Check API and Database health
 */
export const getHealthCheckController = (signal?: AbortSignal) => {
  return customAxios<GetHealthCheckController200>({
    url: `/api/v1/health`,
    method: 'GET',
    signal,
  });
};

export const getGetHealthCheckControllerQueryKey = () => {
  return [`/api/v1/health`] as const;
};

export const getGetHealthCheckControllerQueryOptions = <
  TData = Awaited<ReturnType<typeof getHealthCheckController>>,
  TError =
    | GetHealthCheckController400
    | GetHealthCheckController401
    | GetHealthCheckController404
    | GetHealthCheckController500,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getHealthCheckController>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetHealthCheckControllerQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getHealthCheckController>>> = ({
    signal,
  }) => getHealthCheckController(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getHealthCheckController>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetHealthCheckControllerQueryResult = NonNullable<
  Awaited<ReturnType<typeof getHealthCheckController>>
>;
export type GetHealthCheckControllerQueryError =
  | GetHealthCheckController400
  | GetHealthCheckController401
  | GetHealthCheckController404
  | GetHealthCheckController500;

export function useGetHealthCheckController<
  TData = Awaited<ReturnType<typeof getHealthCheckController>>,
  TError =
    | GetHealthCheckController400
    | GetHealthCheckController401
    | GetHealthCheckController404
    | GetHealthCheckController500,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHealthCheckController>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealthCheckController>>,
          TError,
          Awaited<ReturnType<typeof getHealthCheckController>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetHealthCheckController<
  TData = Awaited<ReturnType<typeof getHealthCheckController>>,
  TError =
    | GetHealthCheckController400
    | GetHealthCheckController401
    | GetHealthCheckController404
    | GetHealthCheckController500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHealthCheckController>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealthCheckController>>,
          TError,
          Awaited<ReturnType<typeof getHealthCheckController>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetHealthCheckController<
  TData = Awaited<ReturnType<typeof getHealthCheckController>>,
  TError =
    | GetHealthCheckController400
    | GetHealthCheckController401
    | GetHealthCheckController404
    | GetHealthCheckController500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHealthCheckController>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Check API and Database health
 */

export function useGetHealthCheckController<
  TData = Awaited<ReturnType<typeof getHealthCheckController>>,
  TError =
    | GetHealthCheckController400
    | GetHealthCheckController401
    | GetHealthCheckController404
    | GetHealthCheckController500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHealthCheckController>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetHealthCheckControllerQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetHealthCheckControllerResponseMock = (
  overrideResponse: Partial<GetHealthCheckController200> = {},
): GetHealthCheckController200 => ({
  success: faker.datatype.boolean(),
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  data: {
    database: {
      status: faker.string.alpha({ length: { min: 10, max: 20 } }),
      latency: faker.string.alpha({ length: { min: 10, max: 20 } }),
    },
  },
  meta: { timestamp: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  ...overrideResponse,
});

export const getGetHealthCheckControllerMockHandler = (
  overrideResponse?:
    | GetHealthCheckController200
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<GetHealthCheckController200> | GetHealthCheckController200),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/v1/health',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetHealthCheckControllerResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};
export const getSystemMock = () => [getGetHealthCheckControllerMockHandler()];
