/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import { faker } from '@faker-js/faker';
import { HttpResponse, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customAxios } from '../axios.client';
import type {
  AssignUserPermissions400,
  AssignUserPermissions401,
  AssignUserPermissions404,
  AssignUserPermissions500,
  AssignUserPermissionsBody,
  GetMe401,
  GetMe404,
  GetMe500,
  GetUser401,
  GetUser404,
  GetUser500,
  UpdateUser400,
  UpdateUser401,
  UpdateUser404,
  UpdateUser500,
  UpdateUserBody,
} from '../model';
import type {
  AssignUserPermissions200,
  GetMe200,
  GetUser200,
  UpdateUser200,
} from '../model';

/**
 * @summary Get a user
 */
export const getMe = (signal?: AbortSignal) => {
  return customAxios<GetMe200>({ url: `/api/v1/users/me`, method: 'GET', signal });
};

export const getGetMeQueryKey = () => {
  return [`/api/v1/users/me`] as const;
};

export const getGetMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = GetMe401 | GetMe404 | GetMe500,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({ signal }) =>
    getMe(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>;
export type GetMeQueryError = GetMe401 | GetMe404 | GetMe500;

export function useGetMe<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = GetMe401 | GetMe404 | GetMe500,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMe<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = GetMe401 | GetMe404 | GetMe500,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMe<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = GetMe401 | GetMe404 | GetMe500,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get a user
 */

export function useGetMe<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = GetMe401 | GetMe404 | GetMe500,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get a user
 */
export const getUser = (id: string, signal?: AbortSignal) => {
  return customAxios<GetUser200>({ url: `/api/v1/users/${id}`, method: 'GET', signal });
};

export const getGetUserQueryKey = (id: string) => {
  return [`/api/v1/users/${id}`] as const;
};

export const getGetUserQueryOptions = <
  TData = Awaited<ReturnType<typeof getUser>>,
  TError = GetUser401 | GetUser404 | GetUser500,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUser>>> = ({ signal }) =>
    getUser(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUser>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserQueryResult = NonNullable<Awaited<ReturnType<typeof getUser>>>;
export type GetUserQueryError = GetUser401 | GetUser404 | GetUser500;

export function useGetUser<
  TData = Awaited<ReturnType<typeof getUser>>,
  TError = GetUser401 | GetUser404 | GetUser500,
>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUser>>,
          TError,
          Awaited<ReturnType<typeof getUser>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUser<
  TData = Awaited<ReturnType<typeof getUser>>,
  TError = GetUser401 | GetUser404 | GetUser500,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUser>>,
          TError,
          Awaited<ReturnType<typeof getUser>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUser<
  TData = Awaited<ReturnType<typeof getUser>>,
  TError = GetUser401 | GetUser404 | GetUser500,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get a user
 */

export function useGetUser<
  TData = Awaited<ReturnType<typeof getUser>>,
  TError = GetUser401 | GetUser404 | GetUser500,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetUserQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update a user
 */
export const updateUser = (
  id: string,
  updateUserBody: UpdateUserBody,
  signal?: AbortSignal,
) => {
  return customAxios<UpdateUser200>({
    url: `/api/v1/users/${id}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updateUserBody,
    signal,
  });
};

export const getUpdateUserMutationOptions = <
  TError = UpdateUser400 | UpdateUser401 | UpdateUser404 | UpdateUser500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateUser>>,
    TError,
    { id: string; data: UpdateUserBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateUser>>,
  TError,
  { id: string; data: UpdateUserBody },
  TContext
> => {
  const mutationKey = ['updateUser'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateUser>>,
    { id: string; data: UpdateUserBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateUser(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateUser>>
>;
export type UpdateUserMutationBody = UpdateUserBody;
export type UpdateUserMutationError =
  | UpdateUser400
  | UpdateUser401
  | UpdateUser404
  | UpdateUser500;

/**
 * @summary Update a user
 */
export const useUpdateUser = <
  TError = UpdateUser400 | UpdateUser401 | UpdateUser404 | UpdateUser500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateUser>>,
      TError,
      { id: string; data: UpdateUserBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateUser>>,
  TError,
  { id: string; data: UpdateUserBody },
  TContext
> => {
  return useMutation(getUpdateUserMutationOptions(options), queryClient);
};
/**
 * @summary Assign permissions to a user
 */
export const assignUserPermissions = (
  id: string,
  assignUserPermissionsBody: AssignUserPermissionsBody,
  signal?: AbortSignal,
) => {
  return customAxios<AssignUserPermissions200>({
    url: `/api/v1/users/${id}/permissions`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: assignUserPermissionsBody,
    signal,
  });
};

export const getAssignUserPermissionsMutationOptions = <
  TError =
    | AssignUserPermissions400
    | AssignUserPermissions401
    | AssignUserPermissions404
    | AssignUserPermissions500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof assignUserPermissions>>,
    TError,
    { id: string; data: AssignUserPermissionsBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof assignUserPermissions>>,
  TError,
  { id: string; data: AssignUserPermissionsBody },
  TContext
> => {
  const mutationKey = ['assignUserPermissions'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof assignUserPermissions>>,
    { id: string; data: AssignUserPermissionsBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return assignUserPermissions(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AssignUserPermissionsMutationResult = NonNullable<
  Awaited<ReturnType<typeof assignUserPermissions>>
>;
export type AssignUserPermissionsMutationBody = AssignUserPermissionsBody;
export type AssignUserPermissionsMutationError =
  | AssignUserPermissions400
  | AssignUserPermissions401
  | AssignUserPermissions404
  | AssignUserPermissions500;

/**
 * @summary Assign permissions to a user
 */
export const useAssignUserPermissions = <
  TError =
    | AssignUserPermissions400
    | AssignUserPermissions401
    | AssignUserPermissions404
    | AssignUserPermissions500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof assignUserPermissions>>,
      TError,
      { id: string; data: AssignUserPermissionsBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof assignUserPermissions>>,
  TError,
  { id: string; data: AssignUserPermissionsBody },
  TContext
> => {
  return useMutation(getAssignUserPermissionsMutationOptions(options), queryClient);
};

export const getGetMeResponseMock = (
  overrideResponse: Partial<GetMe200> = {},
): GetMe200 => ({
  success: faker.datatype.boolean(),
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  data: {
    id: faker.string.uuid(),
    email: faker.internet.email(),
    firstName: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      null,
    ]),
    lastName: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      null,
    ]),
    fullName: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      null,
    ]),
    avatarUrl: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      null,
    ]),
    status: faker.helpers.arrayElement(['active', 'inactive', 'deleted'] as const),
    companyId: faker.helpers.arrayElement([
      faker.helpers.arrayElement([faker.string.uuid(), null]),
      null,
    ]),
    companyName: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      null,
    ]),
    isRoot: faker.datatype.boolean(),
    isOwner: faker.datatype.boolean(),
    permissions: Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
    roleId: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      null,
    ]),
    roleName: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      null,
    ]),
    createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z',
    updatedAt: faker.date.past().toISOString().slice(0, 19) + 'Z',
  },
  meta: { timestamp: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  ...overrideResponse,
});

export const getGetUserResponseMock = (
  overrideResponse: Partial<GetUser200> = {},
): GetUser200 => ({
  success: faker.datatype.boolean(),
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  data: {
    id: faker.string.uuid(),
    email: faker.internet.email(),
    firstName: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      null,
    ]),
    lastName: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      null,
    ]),
    fullName: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      null,
    ]),
    avatarUrl: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      null,
    ]),
    status: faker.helpers.arrayElement(['active', 'inactive', 'deleted'] as const),
    companyId: faker.helpers.arrayElement([
      faker.helpers.arrayElement([faker.string.uuid(), null]),
      null,
    ]),
    companyName: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      null,
    ]),
    isRoot: faker.datatype.boolean(),
    isOwner: faker.datatype.boolean(),
    permissions: Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
    roleId: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      null,
    ]),
    roleName: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      null,
    ]),
    createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z',
    updatedAt: faker.date.past().toISOString().slice(0, 19) + 'Z',
  },
  meta: { timestamp: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  ...overrideResponse,
});

export const getUpdateUserResponseMock = (
  overrideResponse: Partial<UpdateUser200> = {},
): UpdateUser200 => ({
  success: faker.datatype.boolean(),
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  data: {
    email: faker.helpers.arrayElement([faker.internet.email(), undefined]),
    firstName: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      undefined,
    ]),
    lastName: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      undefined,
    ]),
    avatarUrl: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      undefined,
    ]),
    status: faker.helpers.arrayElement([
      faker.helpers.arrayElement(['active', 'inactive', 'deleted'] as const),
      undefined,
    ]),
    roleId: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
  },
  meta: { timestamp: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  ...overrideResponse,
});

export const getAssignUserPermissionsResponseMock = (
  overrideResponse: Partial<AssignUserPermissions200> = {},
): AssignUserPermissions200 => ({
  success: faker.datatype.boolean(),
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  data: {
    id: faker.string.uuid(),
    email: faker.internet.email(),
    firstName: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      null,
    ]),
    lastName: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      null,
    ]),
    fullName: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      null,
    ]),
    avatarUrl: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      null,
    ]),
    status: faker.helpers.arrayElement(['active', 'inactive', 'deleted'] as const),
    companyId: faker.helpers.arrayElement([
      faker.helpers.arrayElement([faker.string.uuid(), null]),
      null,
    ]),
    companyName: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      null,
    ]),
    isRoot: faker.datatype.boolean(),
    isOwner: faker.datatype.boolean(),
    permissions: Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
    roleId: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      null,
    ]),
    roleName: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      null,
    ]),
    createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z',
    updatedAt: faker.date.past().toISOString().slice(0, 19) + 'Z',
  },
  meta: { timestamp: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  ...overrideResponse,
});

export const getGetMeMockHandler = (
  overrideResponse?:
    | GetMe200
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<GetMe200> | GetMe200),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/v1/users/me',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetMeResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getGetUserMockHandler = (
  overrideResponse?:
    | GetUser200
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<GetUser200> | GetUser200),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/v1/users/:id',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetUserResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getUpdateUserMockHandler = (
  overrideResponse?:
    | UpdateUser200
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<UpdateUser200> | UpdateUser200),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    '*/api/v1/users/:id',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getUpdateUserResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getAssignUserPermissionsMockHandler = (
  overrideResponse?:
    | AssignUserPermissions200
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<AssignUserPermissions200> | AssignUserPermissions200),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/api/v1/users/:id/permissions',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getAssignUserPermissionsResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};
export const getUsersMock = () => [
  getGetMeMockHandler(),
  getGetUserMockHandler(),
  getUpdateUserMockHandler(),
  getAssignUserPermissionsMockHandler(),
];
