/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { AcceptInvitation500Error } from './acceptInvitation500Error';
import type { AcceptInvitation500Meta } from './acceptInvitation500Meta';

export type AcceptInvitation500 = {
  success: boolean;
  error: AcceptInvitation500Error;
  meta: AcceptInvitation500Meta;
};
