/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { AcceptInvitation404Error } from './acceptInvitation404Error';
import type { AcceptInvitation404Meta } from './acceptInvitation404Meta';

export type AcceptInvitation404 = {
  success: boolean;
  error: AcceptInvitation404Error;
  meta: AcceptInvitation404Meta;
};
