/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { AcceptInvitation400Error } from './acceptInvitation400Error';
import type { AcceptInvitation400Meta } from './acceptInvitation400Meta';

export type AcceptInvitation400 = {
  success: boolean;
  error: AcceptInvitation400Error;
  meta: AcceptInvitation400Meta;
};
