/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { AcceptInvitation200Data } from './acceptInvitation200Data';
import type { AcceptInvitation200Meta } from './acceptInvitation200Meta';

export type AcceptInvitation200 = {
  success: boolean;
  message?: string;
  data: AcceptInvitation200Data;
  meta: AcceptInvitation200Meta;
};
