/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { AcceptInvitation401Error } from './acceptInvitation401Error';
import type { AcceptInvitation401Meta } from './acceptInvitation401Meta';

export type AcceptInvitation401 = {
  success: boolean;
  error: AcceptInvitation401Error;
  meta: AcceptInvitation401Meta;
};
