/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { AssignUserPermissions400Error } from './assignUserPermissions400Error';
import type { AssignUserPermissions400Meta } from './assignUserPermissions400Meta';

export type AssignUserPermissions400 = {
  success: boolean;
  error: AssignUserPermissions400Error;
  meta: AssignUserPermissions400Meta;
};
