/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */

export type AssignUserPermissionsBodyPermissionKeysItem =
  (typeof AssignUserPermissionsBodyPermissionKeysItem)[keyof typeof AssignUserPermissionsBodyPermissionKeysItem];

export const AssignUserPermissionsBodyPermissionKeysItem = {
  usersread: 'users.read',
  usersinvite: 'users.invite',
  usersupdate: 'users.update',
  usersremove: 'users.remove',
  rolesassign: 'roles.assign',
  companycreate: 'company.create',
  companyread: 'company.read',
  companyupdate: 'company.update',
  companydelete: 'company.delete',
  branchescreate: 'branches.create',
  branchesread: 'branches.read',
  branchesupdate: 'branches.update',
  branchesdelete: 'branches.delete',
  shipmentscreate: 'shipments.create',
  shipmentsread: 'shipments.read',
  shipmentsupdate: 'shipments.update',
  purchasescreate: 'purchases.create',
  purchasesread: 'purchases.read',
  purchasesupdate: 'purchases.update',
} as const;
