/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */

export type AssignUserPermissions200DataStatus =
  (typeof AssignUserPermissions200DataStatus)[keyof typeof AssignUserPermissions200DataStatus];

export const AssignUserPermissions200DataStatus = {
  active: 'active',
  inactive: 'inactive',
  deleted: 'deleted',
} as const;
