/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { AssignUserPermissions500Error } from './assignUserPermissions500Error';
import type { AssignUserPermissions500Meta } from './assignUserPermissions500Meta';

export type AssignUserPermissions500 = {
  success: boolean;
  error: AssignUserPermissions500Error;
  meta: AssignUserPermissions500Meta;
};
