/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { AssignUserPermissions404Error } from './assignUserPermissions404Error';
import type { AssignUserPermissions404Meta } from './assignUserPermissions404Meta';

export type AssignUserPermissions404 = {
  success: boolean;
  error: AssignUserPermissions404Error;
  meta: AssignUserPermissions404Meta;
};
