/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { AssignUserPermissions200Data } from './assignUserPermissions200Data';
import type { AssignUserPermissions200Meta } from './assignUserPermissions200Meta';

export type AssignUserPermissions200 = {
  success: boolean;
  message?: string;
  data: AssignUserPermissions200Data;
  meta: AssignUserPermissions200Meta;
};
