/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { AssignUserPermissions401Error } from './assignUserPermissions401Error';
import type { AssignUserPermissions401Meta } from './assignUserPermissions401Meta';

export type AssignUserPermissions401 = {
  success: boolean;
  error: AssignUserPermissions401Error;
  meta: AssignUserPermissions401Meta;
};
