/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { CreateOwner200Data } from './createOwner200Data';
import type { CreateOwner200Meta } from './createOwner200Meta';

export type CreateOwner200 = {
  success: boolean;
  message?: string;
  data: CreateOwner200Data;
  meta: CreateOwner200Meta;
};
