/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { CreateOwner401Error } from './createOwner401Error';
import type { CreateOwner401Meta } from './createOwner401Meta';

export type CreateOwner401 = {
  success: boolean;
  error: CreateOwner401Error;
  meta: CreateOwner401Meta;
};
