/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { CreateOwner500Error } from './createOwner500Error';
import type { CreateOwner500Meta } from './createOwner500Meta';

export type CreateOwner500 = {
  success: boolean;
  error: CreateOwner500Error;
  meta: CreateOwner500Meta;
};
