/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { CreateOwner404Error } from './createOwner404Error';
import type { CreateOwner404Meta } from './createOwner404Meta';

export type CreateOwner404 = {
  success: boolean;
  error: CreateOwner404Error;
  meta: CreateOwner404Meta;
};
