/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { CreateOwner400Error } from './createOwner400Error';
import type { CreateOwner400Meta } from './createOwner400Meta';

export type CreateOwner400 = {
  success: boolean;
  error: CreateOwner400Error;
  meta: CreateOwner400Meta;
};
