/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteOwner401Error } from './deleteOwner401Error';
import type { DeleteOwner401Meta } from './deleteOwner401Meta';

export type DeleteOwner401 = {
  success: boolean;
  error: DeleteOwner401Error;
  meta: DeleteOwner401Meta;
};
