/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteOwner404Error } from './deleteOwner404Error';
import type { DeleteOwner404Meta } from './deleteOwner404Meta';

export type DeleteOwner404 = {
  success: boolean;
  error: DeleteOwner404Error;
  meta: DeleteOwner404Meta;
};
