/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteOwner500Error } from './deleteOwner500Error';
import type { DeleteOwner500Meta } from './deleteOwner500Meta';

export type DeleteOwner500 = {
  success: boolean;
  error: DeleteOwner500Error;
  meta: DeleteOwner500Meta;
};
