/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { GetHealthCheckController400Error } from './getHealthCheckController400Error';
import type { GetHealthCheckController400Meta } from './getHealthCheckController400Meta';

export type GetHealthCheckController400 = {
  success: boolean;
  error: GetHealthCheckController400Error;
  meta: GetHealthCheckController400Meta;
};
