/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { GetHealthCheckController500Error } from './getHealthCheckController500Error';
import type { GetHealthCheckController500Meta } from './getHealthCheckController500Meta';

export type GetHealthCheckController500 = {
  success: boolean;
  error: GetHealthCheckController500Error;
  meta: GetHealthCheckController500Meta;
};
