/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { GetHealthCheckController200Data } from './getHealthCheckController200Data';
import type { GetHealthCheckController200Meta } from './getHealthCheckController200Meta';

export type GetHealthCheckController200 = {
  success: boolean;
  message?: string;
  data: GetHealthCheckController200Data;
  meta: GetHealthCheckController200Meta;
};
