/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { GetHealthCheckController401Error } from './getHealthCheckController401Error';
import type { GetHealthCheckController401Meta } from './getHealthCheckController401Meta';

export type GetHealthCheckController401 = {
  success: boolean;
  error: GetHealthCheckController401Error;
  meta: GetHealthCheckController401Meta;
};
