/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { GetHealthCheckController200DataDatabase } from './getHealthCheckController200DataDatabase';

export type GetHealthCheckController200Data = {
  database: GetHealthCheckController200DataDatabase;
};
