/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { GetHealthCheckController200Database } from './getHealthCheckController200Database';

export type GetHealthCheckController200 = {
  database: GetHealthCheckController200Database;
};
