/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { GetHealthCheckController404Error } from './getHealthCheckController404Error';
import type { GetHealthCheckController404Meta } from './getHealthCheckController404Meta';

export type GetHealthCheckController404 = {
  success: boolean;
  error: GetHealthCheckController404Error;
  meta: GetHealthCheckController404Meta;
};
