/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { GetMeOwner500Error } from './getMeOwner500Error';
import type { GetMeOwner500Meta } from './getMeOwner500Meta';

export type GetMeOwner500 = {
  success: boolean;
  error: GetMeOwner500Error;
  meta: GetMeOwner500Meta;
};
