/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { GetMe404Error } from './getMe404Error';
import type { GetMe404Meta } from './getMe404Meta';

export type GetMe404 = {
  success: boolean;
  error: GetMe404Error;
  meta: GetMe404Meta;
};
