/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */

export type GetMe200DataRolesItem = {
  id: string;
  name: string;
  description: string;
  isSystemRole: boolean;
};
