/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type GetMe200DataRole =
  | (typeof GetMe200DataRole)[keyof typeof GetMe200DataRole]
  | null;

export const GetMe200DataRole = {
  owner: 'owner',
  manager: 'manager',
  warehouse: 'warehouse',
  branch_staff: 'branch_staff',
} as const;
