/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { GetMe200DataRole } from './getMe200DataRole';

export type GetMe200Data = {
  /** @nullable */
  avatar_url: string | null;
  /** @nullable */
  branch_id: string | null;
  /** @nullable */
  branch_name: string | null;
  /** @nullable */
  business_name: string | null;
  /** @nullable */
  email: string | null;
  /** @nullable */
  is_active: boolean | null;
  /** @nullable */
  is_owner: boolean | null;
  /** @nullable */
  is_root: boolean | null;
  /** @nullable */
  logo_url: string | null;
  /** @nullable */
  name: string | null;
  /** @nullable */
  owner_id: string | null;
  /** @nullable */
  role: GetMe200DataRole;
  /** @nullable */
  user_id: string | null;
};
