/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { GetMeOwner401Error } from './getMeOwner401Error';
import type { GetMeOwner401Meta } from './getMeOwner401Meta';

export type GetMeOwner401 = {
  success: boolean;
  error: GetMeOwner401Error;
  meta: GetMeOwner401Meta;
};
