/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { GetMeOwner404Error } from './getMeOwner404Error';
import type { GetMeOwner404Meta } from './getMeOwner404Meta';

export type GetMeOwner404 = {
  success: boolean;
  error: GetMeOwner404Error;
  meta: GetMeOwner404Meta;
};
