/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { GetMe200DataRolesItem } from './getMe200DataRolesItem';
import type { GetMe200DataStatus } from './getMe200DataStatus';

export type GetMe200Data = {
  id: string;
  email: string;
  /** @nullable */
  firstName: string | null;
  /** @nullable */
  lastName: string | null;
  /** @nullable */
  fullName: string | null;
  /** @nullable */
  avatarUrl: string | null;
  status: GetMe200DataStatus;
  /** @nullable */
  companyId: string | null;
  /** @nullable */
  companyName: string | null;
  isRoot: boolean;
  isOwner: boolean;
  permissions: string[];
  roles: GetMe200DataRolesItem[];
  createdAt: string;
  updatedAt: string;
};
