/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { GetMe401Error } from './getMe401Error';
import type { GetMe401Meta } from './getMe401Meta';

export type GetMe401 = {
  success: boolean;
  error: GetMe401Error;
  meta: GetMe401Meta;
};
