/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { GetMe500Error } from './getMe500Error';
import type { GetMe500Meta } from './getMe500Meta';

export type GetMe500 = {
  success: boolean;
  error: GetMe500Error;
  meta: GetMe500Meta;
};
