/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { GetMe200Data } from './getMe200Data';
import type { GetMe200Meta } from './getMe200Meta';

export type GetMe200 = {
  success: boolean;
  message?: string;
  data: GetMe200Data;
  meta: GetMe200Meta;
};
