/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { GetOnboardingStatus200Data } from './getOnboardingStatus200Data';
import type { GetOnboardingStatus200Meta } from './getOnboardingStatus200Meta';

export type GetOnboardingStatus200 = {
  success: boolean;
  message?: string;
  data: GetOnboardingStatus200Data;
  meta: GetOnboardingStatus200Meta;
};
