/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { GetOwner200Data } from './getOwner200Data';
import type { GetOwner200Meta } from './getOwner200Meta';

export type GetOwner200 = {
  success: boolean;
  message?: string;
  data: GetOwner200Data;
  meta: GetOwner200Meta;
};
