/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */

export type GetOnboardingStatus200Data = {
  company_completed: boolean;
  profile_completed: boolean;
  preferences_completed: boolean;
  onboarding_completed: boolean;
};
