/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { GetOwner404Error } from './getOwner404Error';
import type { GetOwner404Meta } from './getOwner404Meta';

export type GetOwner404 = {
  success: boolean;
  error: GetOwner404Error;
  meta: GetOwner404Meta;
};
