/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { GetOwner401Error } from './getOwner401Error';
import type { GetOwner401Meta } from './getOwner401Meta';

export type GetOwner401 = {
  success: boolean;
  error: GetOwner401Error;
  meta: GetOwner401Meta;
};
