/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { GetOwner500Error } from './getOwner500Error';
import type { GetOwner500Meta } from './getOwner500Meta';

export type GetOwner500 = {
  success: boolean;
  error: GetOwner500Error;
  meta: GetOwner500Meta;
};
