/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { GetOnboardingStatus401Error } from './getOnboardingStatus401Error';
import type { GetOnboardingStatus401Meta } from './getOnboardingStatus401Meta';

export type GetOnboardingStatus401 = {
  success: boolean;
  error: GetOnboardingStatus401Error;
  meta: GetOnboardingStatus401Meta;
};
