/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { GetOnboardingStatus500Error } from './getOnboardingStatus500Error';
import type { GetOnboardingStatus500Meta } from './getOnboardingStatus500Meta';

export type GetOnboardingStatus500 = {
  success: boolean;
  error: GetOnboardingStatus500Error;
  meta: GetOnboardingStatus500Meta;
};
