/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { GetOnboardingStatus404Error } from './getOnboardingStatus404Error';
import type { GetOnboardingStatus404Meta } from './getOnboardingStatus404Meta';

export type GetOnboardingStatus404 = {
  success: boolean;
  error: GetOnboardingStatus404Error;
  meta: GetOnboardingStatus404Meta;
};
