/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { GetUser401Error } from './getUser401Error';
import type { GetUser401Meta } from './getUser401Meta';

export type GetUser401 = {
  success: boolean;
  error: GetUser401Error;
  meta: GetUser401Meta;
};
