/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { GetUser404Error } from './getUser404Error';
import type { GetUser404Meta } from './getUser404Meta';

export type GetUser404 = {
  success: boolean;
  error: GetUser404Error;
  meta: GetUser404Meta;
};
