/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { GetUser500Error } from './getUser500Error';
import type { GetUser500Meta } from './getUser500Meta';

export type GetUser500 = {
  success: boolean;
  error: GetUser500Error;
  meta: GetUser500Meta;
};
