/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { GetUser200Data } from './getUser200Data';
import type { GetUser200Meta } from './getUser200Meta';

export type GetUser200 = {
  success: boolean;
  message?: string;
  data: GetUser200Data;
  meta: GetUser200Meta;
};
