/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */

export type GetUser200DataStatus =
  (typeof GetUser200DataStatus)[keyof typeof GetUser200DataStatus];

export const GetUser200DataStatus = {
  active: 'active',
  inactive: 'inactive',
  deleted: 'deleted',
} as const;
