/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { GetUser200DataStatus } from './getUser200DataStatus';

export type GetUser200Data = {
  id: string;
  email: string;
  /** @nullable */
  firstName: string | null;
  /** @nullable */
  lastName: string | null;
  /** @nullable */
  fullName: string | null;
  /** @nullable */
  avatarUrl: string | null;
  status: GetUser200DataStatus;
  /** @nullable */
  companyId: string | null;
  /** @nullable */
  companyName: string | null;
  isRoot: boolean;
  isOwner: boolean;
  permissions: string[];
  /** @nullable */
  roleId: string | null;
  /** @nullable */
  roleName: string | null;
  createdAt: string;
  updatedAt: string;
};
