/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { InviteUser400Error } from './inviteUser400Error';
import type { InviteUser400Meta } from './inviteUser400Meta';

export type InviteUser400 = {
  success: boolean;
  error: InviteUser400Error;
  meta: InviteUser400Meta;
};
