/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { InviteUser404Error } from './inviteUser404Error';
import type { InviteUser404Meta } from './inviteUser404Meta';

export type InviteUser404 = {
  success: boolean;
  error: InviteUser404Error;
  meta: InviteUser404Meta;
};
