/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { InviteUserOwner401Error } from './inviteUserOwner401Error';
import type { InviteUserOwner401Meta } from './inviteUserOwner401Meta';

export type InviteUserOwner401 = {
  success: boolean;
  error: InviteUserOwner401Error;
  meta: InviteUserOwner401Meta;
};
