/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { InviteUser500Error } from './inviteUser500Error';
import type { InviteUser500Meta } from './inviteUser500Meta';

export type InviteUser500 = {
  success: boolean;
  error: InviteUser500Error;
  meta: InviteUser500Meta;
};
