/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { InviteUser401Error } from './inviteUser401Error';
import type { InviteUser401Meta } from './inviteUser401Meta';

export type InviteUser401 = {
  success: boolean;
  error: InviteUser401Error;
  meta: InviteUser401Meta;
};
