/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { InviteUserOwner400Error } from './inviteUserOwner400Error';
import type { InviteUserOwner400Meta } from './inviteUserOwner400Meta';

export type InviteUserOwner400 = {
  success: boolean;
  error: InviteUserOwner400Error;
  meta: InviteUserOwner400Meta;
};
