/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { InviteUserOwner404Error } from './inviteUserOwner404Error';
import type { InviteUserOwner404Meta } from './inviteUserOwner404Meta';

export type InviteUserOwner404 = {
  success: boolean;
  error: InviteUserOwner404Error;
  meta: InviteUserOwner404Meta;
};
