/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { InviteUserOwner200Data } from './inviteUserOwner200Data';
import type { InviteUserOwner200Meta } from './inviteUserOwner200Meta';

export type InviteUserOwner200 = {
  success: boolean;
  message?: string;
  data: InviteUserOwner200Data;
  meta: InviteUserOwner200Meta;
};
