/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { InviteUserOwner500Error } from './inviteUserOwner500Error';
import type { InviteUserOwner500Meta } from './inviteUserOwner500Meta';

export type InviteUserOwner500 = {
  success: boolean;
  error: InviteUserOwner500Error;
  meta: InviteUserOwner500Meta;
};
