/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */

export type ListOwnersSortDir =
  (typeof ListOwnersSortDir)[keyof typeof ListOwnersSortDir];

export const ListOwnersSortDir = {
  asc: 'asc',
  desc: 'desc',
} as const;
