/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { ListOwners500Error } from './listOwners500Error';
import type { ListOwners500Meta } from './listOwners500Meta';

export type ListOwners500 = {
  success: boolean;
  error: ListOwners500Error;
  meta: ListOwners500Meta;
};
