/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { ListOwners404Error } from './listOwners404Error';
import type { ListOwners404Meta } from './listOwners404Meta';

export type ListOwners404 = {
  success: boolean;
  error: ListOwners404Error;
  meta: ListOwners404Meta;
};
