/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { ListOwners401Error } from './listOwners401Error';
import type { ListOwners401Meta } from './listOwners401Meta';

export type ListOwners401 = {
  success: boolean;
  error: ListOwners401Error;
  meta: ListOwners401Meta;
};
