/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { ListOwnersSortBy } from './listOwnersSortBy';
import type { ListOwnersSortDir } from './listOwnersSortDir';

export type ListOwnersParams = {
  /**
   * @minimum 1
   */
  page?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  pageSize?: number;
  search?: string;
  /**
   * @nullable
   */
  isActive?: boolean | null;
  sortBy?: ListOwnersSortBy;
  sortDir?: ListOwnersSortDir;
};
