/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { ListOwners200DataItem } from './listOwners200DataItem';
import type { ListOwners200Meta } from './listOwners200Meta';

export type ListOwners200 = {
  success: boolean;
  message?: string;
  data: ListOwners200DataItem[];
  meta: ListOwners200Meta;
};
