/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */

export type ListOwnersSortBy = (typeof ListOwnersSortBy)[keyof typeof ListOwnersSortBy];

export const ListOwnersSortBy = {
  created_at: 'created_at',
  name: 'name',
  business_name: 'business_name',
} as const;
