/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */

export type ListOwners200 = {
  id: string;
  name: string;
  email: string;
  /** @nullable */
  phone: string | null;
  businessName: string;
  /** @nullable */
  logoUrl: string | null;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
};
