/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { ListOwners400Error } from './listOwners400Error';
import type { ListOwners400Meta } from './listOwners400Meta';

export type ListOwners400 = {
  success: boolean;
  error: ListOwners400Error;
  meta: ListOwners400Meta;
};
