/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateUserBodyRole } from './updateUserBodyRole';

export type UpdateUserBody = {
  avatar_url?: string;
  branch_id?: string;
  email?: string;
  is_active?: boolean;
  name?: string;
  owner_id?: string;
  role?: UpdateUserBodyRole;
};
