/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateUser200Data } from './updateUser200Data';
import type { UpdateUser200Meta } from './updateUser200Meta';

export type UpdateUser200 = {
  success: boolean;
  message?: string;
  data: UpdateUser200Data;
  meta: UpdateUser200Meta;
};
