/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */

export type UpdateProfileBodyRole =
  (typeof UpdateProfileBodyRole)[keyof typeof UpdateProfileBodyRole];

export const UpdateProfileBodyRole = {
  owner: 'owner',
  manager: 'manager',
  warehouse: 'warehouse',
  branch_staff: 'branch_staff',
} as const;
