/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateCompany500Error } from './updateCompany500Error';
import type { UpdateCompany500Meta } from './updateCompany500Meta';

export type UpdateCompany500 = {
  success: boolean;
  error: UpdateCompany500Error;
  meta: UpdateCompany500Meta;
};
