/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateUser401Error } from './updateUser401Error';
import type { UpdateUser401Meta } from './updateUser401Meta';

export type UpdateUser401 = {
  success: boolean;
  error: UpdateUser401Error;
  meta: UpdateUser401Meta;
};
