/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateOwner200Data } from './updateOwner200Data';
import type { UpdateOwner200Meta } from './updateOwner200Meta';

export type UpdateOwner200 = {
  success: boolean;
  message?: string;
  data: UpdateOwner200Data;
  meta: UpdateOwner200Meta;
};
