/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { UpdatePreferences500Error } from './updatePreferences500Error';
import type { UpdatePreferences500Meta } from './updatePreferences500Meta';

export type UpdatePreferences500 = {
  success: boolean;
  error: UpdatePreferences500Error;
  meta: UpdatePreferences500Meta;
};
