/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateCompany401Error } from './updateCompany401Error';
import type { UpdateCompany401Meta } from './updateCompany401Meta';

export type UpdateCompany401 = {
  success: boolean;
  error: UpdateCompany401Error;
  meta: UpdateCompany401Meta;
};
