/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */

export type UpdateCompanyBody = {
  /** @minLength 1 */
  company_name: string;
  logo_url?: string;
};
