/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateProfile404Error } from './updateProfile404Error';
import type { UpdateProfile404Meta } from './updateProfile404Meta';

export type UpdateProfile404 = {
  success: boolean;
  error: UpdateProfile404Error;
  meta: UpdateProfile404Meta;
};
