/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type UpdateUser200DataRole =
  | (typeof UpdateUser200DataRole)[keyof typeof UpdateUser200DataRole]
  | null;

export const UpdateUser200DataRole = {
  owner: 'owner',
  manager: 'manager',
  warehouse: 'warehouse',
  branch_staff: 'branch_staff',
} as const;
