/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */

export type UpdateUser200DataStatus =
  (typeof UpdateUser200DataStatus)[keyof typeof UpdateUser200DataStatus];

export const UpdateUser200DataStatus = {
  active: 'active',
  inactive: 'inactive',
  deleted: 'deleted',
} as const;
