/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateUser500Error } from './updateUser500Error';
import type { UpdateUser500Meta } from './updateUser500Meta';

export type UpdateUser500 = {
  success: boolean;
  error: UpdateUser500Error;
  meta: UpdateUser500Meta;
};
