/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { UpdatePreferences404Error } from './updatePreferences404Error';
import type { UpdatePreferences404Meta } from './updatePreferences404Meta';

export type UpdatePreferences404 = {
  success: boolean;
  error: UpdatePreferences404Error;
  meta: UpdatePreferences404Meta;
};
