/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateUserBodyStatus } from './updateUserBodyStatus';

export type UpdateUserBody = {
  email?: string;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  avatarUrl?: string | null;
  status?: UpdateUserBodyStatus;
  roleId?: string;
};
