/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { UpdatePreferences400Error } from './updatePreferences400Error';
import type { UpdatePreferences400Meta } from './updatePreferences400Meta';

export type UpdatePreferences400 = {
  success: boolean;
  error: UpdatePreferences400Error;
  meta: UpdatePreferences400Meta;
};
