/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateCompany400Error } from './updateCompany400Error';
import type { UpdateCompany400Meta } from './updateCompany400Meta';

export type UpdateCompany400 = {
  success: boolean;
  error: UpdateCompany400Error;
  meta: UpdateCompany400Meta;
};
