/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateOwner401Error } from './updateOwner401Error';
import type { UpdateOwner401Meta } from './updateOwner401Meta';

export type UpdateOwner401 = {
  success: boolean;
  error: UpdateOwner401Error;
  meta: UpdateOwner401Meta;
};
