/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { UpdatePreferences401Error } from './updatePreferences401Error';
import type { UpdatePreferences401Meta } from './updatePreferences401Meta';

export type UpdatePreferences401 = {
  success: boolean;
  error: UpdatePreferences401Error;
  meta: UpdatePreferences401Meta;
};
