/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateOwner400Error } from './updateOwner400Error';
import type { UpdateOwner400Meta } from './updateOwner400Meta';

export type UpdateOwner400 = {
  success: boolean;
  error: UpdateOwner400Error;
  meta: UpdateOwner400Meta;
};
