/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateOwner500Error } from './updateOwner500Error';
import type { UpdateOwner500Meta } from './updateOwner500Meta';

export type UpdateOwner500 = {
  success: boolean;
  error: UpdateOwner500Error;
  meta: UpdateOwner500Meta;
};
