/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateProfile400Error } from './updateProfile400Error';
import type { UpdateProfile400Meta } from './updateProfile400Meta';

export type UpdateProfile400 = {
  success: boolean;
  error: UpdateProfile400Error;
  meta: UpdateProfile400Meta;
};
