/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateProfile500Error } from './updateProfile500Error';
import type { UpdateProfile500Meta } from './updateProfile500Meta';

export type UpdateProfile500 = {
  success: boolean;
  error: UpdateProfile500Error;
  meta: UpdateProfile500Meta;
};
