/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateCompany404Error } from './updateCompany404Error';
import type { UpdateCompany404Meta } from './updateCompany404Meta';

export type UpdateCompany404 = {
  success: boolean;
  error: UpdateCompany404Error;
  meta: UpdateCompany404Meta;
};
