/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateUser404Error } from './updateUser404Error';
import type { UpdateUser404Meta } from './updateUser404Meta';

export type UpdateUser404 = {
  success: boolean;
  error: UpdateUser404Error;
  meta: UpdateUser404Meta;
};
