/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateUser400Error } from './updateUser400Error';
import type { UpdateUser400Meta } from './updateUser400Meta';

export type UpdateUser400 = {
  success: boolean;
  error: UpdateUser400Error;
  meta: UpdateUser400Meta;
};
