/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateProfile401Error } from './updateProfile401Error';
import type { UpdateProfile401Meta } from './updateProfile401Meta';

export type UpdateProfile401 = {
  success: boolean;
  error: UpdateProfile401Error;
  meta: UpdateProfile401Meta;
};
