/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateOwner404Error } from './updateOwner404Error';
import type { UpdateOwner404Meta } from './updateOwner404Meta';

export type UpdateOwner404 = {
  success: boolean;
  error: UpdateOwner404Error;
  meta: UpdateOwner404Meta;
};
