/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { ValidateInvitation404Error } from './validateInvitation404Error';
import type { ValidateInvitation404Meta } from './validateInvitation404Meta';

export type ValidateInvitation404 = {
  success: boolean;
  error: ValidateInvitation404Error;
  meta: ValidateInvitation404Meta;
};
