/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */

export type ValidateInvitation200Role =
  (typeof ValidateInvitation200Role)[keyof typeof ValidateInvitation200Role];

export const ValidateInvitation200Role = {
  owner: 'owner',
  manager: 'manager',
  warehouse: 'warehouse',
  branch_staff: 'branch_staff',
} as const;
