/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { ValidateInvitation400Error } from './validateInvitation400Error';
import type { ValidateInvitation400Meta } from './validateInvitation400Meta';

export type ValidateInvitation400 = {
  success: boolean;
  error: ValidateInvitation400Error;
  meta: ValidateInvitation400Meta;
};
