/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { ValidateInvitation200DataRole } from './validateInvitation200DataRole';

export type ValidateInvitation200Data = {
  email: string;
  role: ValidateInvitation200DataRole;
};
