/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { ValidateInvitation500Error } from './validateInvitation500Error';
import type { ValidateInvitation500Meta } from './validateInvitation500Meta';

export type ValidateInvitation500 = {
  success: boolean;
  error: ValidateInvitation500Error;
  meta: ValidateInvitation500Meta;
};
