/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { ValidateInvitation401Error } from './validateInvitation401Error';
import type { ValidateInvitation401Meta } from './validateInvitation401Meta';

export type ValidateInvitation401 = {
  success: boolean;
  error: ValidateInvitation401Error;
  meta: ValidateInvitation401Meta;
};
