/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Backend Store Check
 * API for storage and management of products and users
 * OpenAPI spec version: 1.0.0
 */
import type { ValidateInvitation200Data } from './validateInvitation200Data';
import type { ValidateInvitation200Meta } from './validateInvitation200Meta';

export type ValidateInvitation200 = {
  success: boolean;
  message?: string;
  data: ValidateInvitation200Data;
  meta: ValidateInvitation200Meta;
};
