const ENV = import.meta.env;

export const env = {
  DEV: ENV.DEV,
  PROD: ENV.PROD,
  MODE: ENV.MODE,
  API_URL: ENV.VITE_API_URL,
  API_URL_DEV: ENV.VITE_API_URL_DEV,
  SUPABASE_URL: ENV.VITE_SUPABASE_URL,
  SUPABASE_ANON_KEY: ENV.VITE_SUPABASE_ANON_KEY,
} as const;
